{"name": "test_get_login_submit", "status": "failed", "statusDetails": {"message": "AssertionError: assert '2' == '0'\n  - 2\n  + 0", "trace": "self = <tests.test_testcase.TestSingle object at 0x10aaa5da0>\n\n    @allure.story(\"测试3\")\n    def test_get_login_submit(self):\n        \"\"\" 呵呵呵呵1234\"\"\"\n        single_testcase_yaml = os.path.join(os.path.dirname(__file__), \"api\", \"get_login_submit.yml\")\n    \n        result = self.run.run_yml(single_testcase_yaml)\n        logger.info(\"666666666\"+str(result))\n        for ass in result[0]:\n            logger.info(\"hehjehehehhhjhjhjhejhjehjehje\")\n            logger.info(ass[\"url\"])\n            logger.info(\"=======Assert=====\")\n            logger.info(\"expected:\" + '\\n\\t' + \"{}={}\".format(\"expected\", ass[\"expected\"]))\n            logger.info(\"actual:\" + '\\n\\t' + \"{}={}\".format(\"actual\", ass[\"actual\"]))\n            try:\n>               assert ass[\"expected\"] == ass[\"actual\"]\nE               AssertionError: assert '2' == '0'\nE                 - 2\nE                 + 0\n\ntest_testcase.py:75: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_testcase.TestSingle object at 0x10aaa5da0>\n\n    @allure.story(\"测试3\")\n    def test_get_login_submit(self):\n        \"\"\" 呵呵呵呵1234\"\"\"\n        single_testcase_yaml = os.path.join(os.path.dirname(__file__), \"api\", \"get_login_submit.yml\")\n    \n        result = self.run.run_yml(single_testcase_yaml)\n        logger.info(\"666666666\"+str(result))\n        for ass in result[0]:\n            logger.info(\"hehjehehehhhjhjhjhejhjehjehje\")\n            logger.info(ass[\"url\"])\n            logger.info(\"=======Assert=====\")\n            logger.info(\"expected:\" + '\\n\\t' + \"{}={}\".format(\"expected\", ass[\"expected\"]))\n            logger.info(\"actual:\" + '\\n\\t' + \"{}={}\".format(\"actual\", ass[\"actual\"]))\n            try:\n                assert ass[\"expected\"] == ass[\"actual\"]\n            except AssertionError:\n>               assert ass[\"expected\"] == ass[\"actual\"]\nE               AssertionError: assert '2' == '0'\nE                 - 2\nE                 + 0\n\ntest_testcase.py:77: AssertionError"}, "description": " 呵呵呵呵1234", "attachments": [{"name": "log", "source": "37547921-8ddf-4162-9c70-7fc45f543608-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1cede81b-6511-481c-9b9f-dfa4c79dd718-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "5fb3a4d0-238f-4e58-8b6d-44fd346179b7-attachment.txt", "type": "text/plain"}], "start": 1576602076314, "stop": 1576602076619, "uuid": "1c1204e1-64ac-4c47-8063-0d35b0b3e71e", "historyId": "9d45b30fd97667aff13f3a162735a3a9", "fullName": "test_testcase.TestSingle#test_get_login_submit", "labels": [{"name": "feature", "value": "测试接口"}, {"name": "story", "value": "测试3"}, {"name": "suite", "value": "test_testcase"}, {"name": "subSuite", "value": "TestSingle"}, {"name": "host", "value": "anxiaodongdeMacBook-Pro.local"}, {"name": "thread", "value": "7144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_testcase"}]}