{"name": "test_run_testcase_yml", "status": "broken", "statusDetails": {"message": "KeyError: 'confing'", "trace": "self = <tests.test_testcase.TestSingle object at 0x10a298630>\n\n    @allure.story(\"测试1\")\n    def test_run_testcase_yml(self):\n        \"\"\"\n    \n            斤斤计较测试\n        \"\"\"\n        single_testcase_yaml = os.path.join(os.path.dirname(__file__), \"testcase\", \"mubu_login.yml\")\n>       result = self.run.run_yml(single_testcase_yaml)\n\ntest_testcase.py:49: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../htturunner/runner.py:253: in run_yml\n    success = self.run_api(api_info)\n../htturunner/runner.py:58: in run_api\n    self.get_run_api(api_info)  # 判断是否获取依赖接口\n../htturunner/runner.py:267: in get_run_api\n    self.run_yml(ru_path)\n../htturunner/runner.py:253: in run_yml\n    success = self.run_api(api_info)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <htturunner.runner.Runapi object at 0x10560c080>\napi_info = {'extract': {'code': '$.code', 'msg': '$.msg'}, 'name': 'https://mubu.com/api/login/submit', 'request': {'data': {'pas...e Gecko) Chrome/78.0.3904.97 Safari/537.36 '}, 'method': 'POST', 'url': 'api/login/submit'}, 'validate': {'$.code': 0}}\n\n    def run_api(self, api_info):\n        \"\"\"\n    \n        :param api:\n            {\n                \"request\": {},\n                \"validate\": {}\n            }\n        :return:\n    \n        \"\"\"\n        warnings.simplefilter(\"ignore\", ResourceWarning)\n        self.get_run_api(api_info)  # 判断是否获取依赖接口\n        request = api_info[\"request\"]\n        global session_variables_mapping\n        global result\n        global result_dict\n    \n        # 有config时执行以下代码\n>       if all_veriables_mapping[\"confing\"]:\nE       KeyError: 'confing'\n\n../htturunner/runner.py:65: KeyError"}, "description": "\n\n            斤斤计较测试\n        ", "attachments": [{"name": "log", "source": "273fcf3e-a226-4695-851c-7651ceb0541d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1e18f926-56b7-42ba-829f-9eeedb9dda92-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "eb9725a5-6193-4172-8cf6-408771f2278d-attachment.txt", "type": "text/plain"}], "start": 1577112336855, "stop": 1577112336875, "uuid": "0fd14fae-054d-47ac-8c8b-366a320b3730", "historyId": "a795ec9b90752ada9e41d5e5673b3878", "fullName": "test_testcase.TestSingle#test_run_testcase_yml", "labels": [{"name": "feature", "value": "测试接口"}, {"name": "story", "value": "测试1"}, {"name": "suite", "value": "test_testcase"}, {"name": "subSuite", "value": "TestSingle"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "9883-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_testcase"}]}